spring:
  application:
    name: Worldcup2026
  threads:
    virtual:
      enabled: true
  ai:
    google:
      genai:
        api-key: ${GOOGLE_AI_API_KEY}
        chat:
          model: gemini-3.5-flash
