spring:
  application:
    name: Worldcup2026
  threads:
    virtual:
      enabled: true
  ai:
    google:
      genai:
        api-key: ${GOOGLE_AI_API_KEY}
        chat:
          model: gemini-3.1-pro-preview
          flash-model: gemini-3.5-flash
          flash-lite-model: gemini-3.1-flash-lite
          google-search-retrieval: true
          include-server-side-tool-invocations: true
          thinking-budget: 8192
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
  datasource:
    url: jdbc:postgresql://localhost:5432/worldcup
    username: worldcup
    password: worldcup

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG